theme = "dark_plus"

[editor]
true-color = true
line-number = "relative"
mouse = false
bufferline = "always"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
G = "goto_file_end"
X = "extend_line_above"

[keys.normal.space]
q = ":quit"
w = ":write"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false